version: '3.6'

services:
  db:
    image: mysql:5-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=acquire
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./tmp/db:/var/lib/mysql

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'

  acquire-applications-api:
    build:
      context: .
      dockerfile: scripts/acquire-applications-api.Dockerfile.Build
    links:
      - db
      - redis
    ports:
      - '3333:3333'

  acquire-quote-api:
    build:
      context: .
      dockerfile: scripts/acquire-quote-api.Dockerfile.Build
    links:
      - db
      - redis
    ports:
      - '4000:4000'

  mock-fast-api:
    build:
      context: .
      dockerfile: scripts/mock-fast-api.Dockerfile.Build
    command: sleep 10000
    links:
      - db
      - redis
    ports:
      - '3000:3000'
