version: '3.6'

services:
  db:
    image: mysql:5-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=acquire
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./tmp/db:/var/lib/mysql

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'

  acquire-applications-api:
    build: .
    command: nx serve acquire-applications-api --watch
    links:
      - db
      - redis
    ports:
      - '3333:3333'
    volumes:
      - .:/app

  acquire-quote-api:
    build: .
    command: nx serve acquire-quote-api --watch
    links:
      - db
      - redis
    ports:
      - '4000:4000'
    volumes:
      - .:/app

  mock-fast-api:
    build: .
    command: nx serve mock-fast-api --watch
    links:
      - db
      - redis
    ports:
      - '3000:3000'
    volumes:
      - .:/app
