// import * as fs from 'fs';
// import * as path from 'path';
// import { parse } from 'csv-parse/sync';

import { OLI_LU } from '../../types';

import GENDER from './tables/GENDER.json';
import ISSUETYPE from './tables/ISSUETYPE.json';
import PARTY from './tables/PARTY.json';
import REPLACETYPE from './tables/REPLACETYPE.json';
import NLGPERIOD from './tables/NLGPERIOD.json';
import BASICATTACHMENTTYPE from './tables/BASICATTACHMENTTYPE.json';
import ATTACHMENTTYPE from './tables/ATTACHMENTTYPE.json';
import REQCODE from './tables/REQCODE.json';

import QUALPLANTYPE from './tables/QUALPLANTYPE.json';
import LIFECOVSTATUS from './tables/LIFECOVSTATUS.json';
import TOBACCOPREMIMUMBASIS from './tables/TOBACCOPREMIMUMBASIS.json';
import INDICATORCODE from './tables/INDICATORCODE.json';
import LIVESTYPE from './tables/LIVESTYPE.json';
import DEATHBENEFITOPTTYPE from './tables/DEATHBENEFITOPTTYPE.json';
import LIFECOVOPTTYPECODE from './tables/LIFECOVOPTTYPECODE.json';
import LIFEPARTICIPANTROLECODE from './tables/LIFEPARTICIPANTROLECODE.json';
import DEFLIFEINSMETHOD from './tables/DEFLIFEINSMETHOD.json';
import INTERNAL1035 from './tables/INTERNAL1035.json';

import TRANSTYPE from './tables/TRANSTYPE.json';
import TRANSMODE from './tables/TRANSMODE.json';
import PAYMENTMODE from './tables/PAYMENTMODE.json';
import PAYMENTMETHOD from './tables/PAYMENTMETHOD.json';
import HOLDINGTYPE from './tables/HOLDINGTYPE.json';
import LINEOFBUSINESS from './tables/LINEOFBUSINESS.json';
import PRODUCTTYPE from './tables/PRODUCTTYPE.json';
import APPLICATIONTYPE from './tables/APPLICATIONTYPE.json';
import APPLICATIONJURISDICTION from './tables/APPLICATIONJURISDICTION.json';
import FORMALAPPIND from './tables/FORMALAPPIND.json';
import SUBMISSIONTYPE from './tables/SUBMISSIONTYPE.json';
import REPLACEMENTIND from './tables/REPLACEMENTIND.json';
import SIGNATUREROLECODE from './tables/SIGNATUREROLECODE.json';
import UNDERWRITINGDECISIONMRAS from './tables/UNDERWRITINGDECISIONMRAS.json';

import ARRTYPE from './tables/ARRTYPE.json';
import TRANSFERAMTTYPE from './tables/TRANSFERAMTTYPE.json';
import CITIZENSHIP from './tables/CITIZENSHIP.json';
import BIRTHJURISDICTIONTC from './tables/BIRTHJURISDICTIONTC.json';
import MARSTAT from './tables/MARSTAT.json';
import GOVTIDTC from './tables/GOVTIDTC.json';
import RELATIONDESCRIPTION from './tables/RELATIONDESCRIPTION.json';
import ADDRESSSTATETC from './tables/ADDRESSSTATETC.json';
import PARTYTYPECODE from './tables/PARTYTYPECODE.json';
import BENEFICIARYDESIGNATION from './tables/BENEFICIARYDESIGNATION.json';
import ORIGINATINGOBJECTTYPE from './tables/ORIGIBATINGOBJECTTYPE.json';
import RELATEDOBJECTTYPE from './tables/RELATEDOBJECTTYPE.json';
import RELATIONROLECODE from './tables/RELATIONROLECODE.json';
import ORGFORM from './tables/ORGFORM.json';

import MILITARYORGANIZATIONTYPE from './tables/MILITARYORGANIZATIONTYPE.json';
import MILITARYSTATUS from './tables/MILITARYSTATUS.json';
import MECIND from './tables/MECIND.json';
import DISTRIBUTIONCHANNEL from './tables/DISTRIBUTIONCHANNEL.json';
import BACKSTAGETYPE from './tables/BACKSTAGETYPE.json';
import ARRMODE from './tables/ARRMODE.json';
import PHYSICIANSPECIALITY from './tables/PHYSICIANSPECIALITY.json';
import DISTCHAN from './tables/DISTCHAN.json';
import ADDRESSCOUNTRYTC from './tables/ADDRESSCOUNTRYTC.json';
import DRIVERSLICENSESTATE from './tables/DRIVERSLICENSESTATE.json';
import VIPIND from './tables/VIPIND.json';
import HOLDINGSTATUS from './tables/HOLDINGSTATUS.json';
import ADDRESSTYPECODE from './tables/ADDRESSTYPECODE.json';
import BACKDATETYPE from './tables/BACKSTAGETYPE.json';
import BANKACCTYPE from './tables/BANKACCTYPE.json';
import RATECLASS from './tables/RATECLASS.json';
// fs.writeFileSync(
//   path.resolve(`${__dirname}/tables/`, 'ISSUETYPE.json'),
//   JSON.stringify(
//     parse(
//       fs.readFileSync(
//         path.resolve(`${__dirname}/tables/`, 'ISSUETYPE.csv'),
//         'utf-8'
//       )
//     ),
//     null,
//     2
//   )
// );

// Lookup<OLI_LU>
const tables: Map<OLI_LU, (string | number)[][]> = new Map([
  [OLI_LU.GENDER, GENDER],
  [OLI_LU.ISSUETYPE, ISSUETYPE],
  [OLI_LU.PARTY, PARTY],
  [OLI_LU.REPLACETYPE, REPLACETYPE],
  [OLI_LU.NLGPERIOD, NLGPERIOD],
  [OLI_LU.QUALPLANTYPE, QUALPLANTYPE],
  [OLI_LU.LIFECOVSTATUS, LIFECOVSTATUS],
  [OLI_LU.TOBACCOPREMIMUMBASIS, TOBACCOPREMIMUMBASIS],
  [OLI_LU.INDICATORCODE, INDICATORCODE],
  [OLI_LU.LIVESTYPE, LIVESTYPE],
  [OLI_LU.DEATHBENEFITOPTTYPE, DEATHBENEFITOPTTYPE],
  [OLI_LU.LIFECOVOPTTYPECODE, LIFECOVOPTTYPECODE],
  [OLI_LU.LIFEPARTICIPANTROLECODE, LIFEPARTICIPANTROLECODE],
  [OLI_LU.DEFLIFEINSMETHOD, DEFLIFEINSMETHOD],
  [OLI_LU.INTERNAL1035, INTERNAL1035],
  [OLI_LU.TRANSTYPE, TRANSTYPE],
  [OLI_LU.TRANSMODE, TRANSMODE],
  [OLI_LU.PAYMENTMODE, PAYMENTMODE],
  [OLI_LU.PAYMENTMETHOD, PAYMENTMETHOD],
  [OLI_LU.HOLDINGTYPE, HOLDINGTYPE],
  [OLI_LU.LINEOFBUSINESS, LINEOFBUSINESS],
  [OLI_LU.PRODUCTTYPE, PRODUCTTYPE],
  [OLI_LU.APPLICATIONTYPE, APPLICATIONTYPE],
  [OLI_LU.APPLICATIONJURISDICTION, APPLICATIONJURISDICTION],
  [OLI_LU.FORMALAPPIND, FORMALAPPIND],
  [OLI_LU.SUBMISSIONTYPE, SUBMISSIONTYPE],
  [OLI_LU.REPLACEMENTIND, REPLACEMENTIND],
  [OLI_LU.SIGNATUREROLECODE, SIGNATUREROLECODE],
  [OLI_LU.ARRTYPE, ARRTYPE],
  [OLI_LU.TRANSFERAMTTYPE, TRANSFERAMTTYPE],
  [OLI_LU.BASICATTACHMENTTYPE, BASICATTACHMENTTYPE],
  [OLI_LU.ATTACHMENTTYPE, ATTACHMENTTYPE],
  [OLI_LU.REQCODE, REQCODE],
  [OLI_LU.UNDERWRITINGDECISIONMRAS, UNDERWRITINGDECISIONMRAS],
  [OLI_LU.CITIZENSHIP, CITIZENSHIP],
  [OLI_LU.BIRTHJURISDICTIONTC, BIRTHJURISDICTIONTC],
  [OLI_LU.MARSTAT, MARSTAT],
  [OLI_LU.GOVTIDTC, GOVTIDTC],
  [OLI_LU.RELATIONDESCRIPTION, RELATIONDESCRIPTION],
  [OLI_LU.ADDRESSSTATETC, ADDRESSSTATETC],
  [OLI_LU.BENEFICIARYDESIGNATION, BENEFICIARYDESIGNATION],
  [OLI_LU.PARTYTYPECODE, PARTYTYPECODE],
  [OLI_LU.ORIGINATINGOBJECTTYPE, ORIGINATINGOBJECTTYPE],
  [OLI_LU.RELATEDOBJECTTYPE, RELATEDOBJECTTYPE],
  [OLI_LU.RELATIONROLECODE, RELATIONROLECODE],
  [OLI_LU.ORGFORM, ORGFORM],
  [OLI_LU.MILITARYORGANIZATIONTYPE, MILITARYORGANIZATIONTYPE],
  [OLI_LU.MILITARYSTATUS, MILITARYSTATUS],
  [OLI_LU.MECIND, MECIND],
  [OLI_LU.DISTRIBUTIONCHANNEL, DISTRIBUTIONCHANNEL],
  [OLI_LU.BACKSTAGETYPE, BACKSTAGETYPE],
  [OLI_LU.ARRMODE, ARRMODE],
  [OLI_LU.PHYSICIANSPECIALITY, PHYSICIANSPECIALITY],
  [OLI_LU.DISTCHAN, DISTCHAN],
  [OLI_LU.ADDRESSCOUNTRYTC, ADDRESSCOUNTRYTC],
  [OLI_LU.DRIVERSLICENSESTATE, DRIVERSLICENSESTATE],
  [OLI_LU.VIPIND, VIPIND],
  [OLI_LU.HOLDINGSTATUS, HOLDINGSTATUS],
  [OLI_LU.ADDRESSTYPECODE, ADDRESSTYPECODE],
  [OLI_LU.BACKDATETYPE, BACKDATETYPE],
  [OLI_LU.BANKACCTYPE, BANKACCTYPE],
  [OLI_LU.RATECLASS, RATECLASS],
  // [OLI_LU.PROCESSINGINSTRUCTION]: '',
]);

export default tables;
