export class CreateUserDto {
  invitation_type?: number; // int(11)
  name?: string; // varbinary(2550)
  email?: string; // varbinary(2550)
  password?: string; // varchar(255)
  agency_id?: number; // int(11)
  agent_code?: string; // varbinary(2550)
  user_type?: number; // int(11)
  phone_number?: string; // varbinary(2550)
  status?: number; // int(11)
  login_attempts?: number; // int(11)
  last_login?: string; // datetime
  active_status?: number; // int(11)
  row_status?: 0 | 1; // tinyint(1)
  user_unique_id?: string; // varbinary(2550)
  fb_access_token?: string; // varbinary(2550)
  last_fb_sync_date?: string; // datetime
  access_token_error?: string; // varchar(255)
  fb_flag?: number; // tinyint(1)
  confirm_status?: number; // tinyint(1)
  onboard_activity?: number; // int(11)
  onboarding_tracking?: object; // json
  otp?: string; // varchar(255)
  otp_sent_time?: string; // datetime
  user_session_id?: number; // int(11)
  created_time?: string; // datetime
  modified_time?: string; // timestamp
  random_user_id?: string; // varchar(255)
  validic_token_response?: string; // varbinary(2550)
  validic_access_token?: string; // varbinary(2550)
  carrier_id?: number; // int(11)
  password_randomid?: string; // varchar(255)
  password_reset_date?: string; // datetime
  user_timezone?: string; // varchar(50)
  timezone_name?: string; // varchar(255)
  endorsement_delivery?: number; // tinyint(1)
  amendment_acceptance?: number; // tinyint(4)
  agent_id?: number; // int(11)
  socotra_policy_holder_locator?: string; // varchar(255)
  socotra_policy_locator?: string; // varchar(255)
  auth_code?: string; // varchar(255)
  auth_code_sent_time?: string; // datetime
  carrier_consumer_id?: string; // varchar(255)
  last_updated?: string; // datetime
  is_agency_admin?: number; // tinyint(1)
  archive_status?: number; // tinyint(1)
  reassign_status?: number; // tinyint(1)
  policy_holder_id?: string; // varbinary(2550)
  unique_id?: string; // varchar(100)
  type_of_user?: string; // varchar(255)
}
