/*
 * Jenkins URL: https://jenkins.sureifylifeco.com/job/Product-Acquire/job/acquire-apps/
**/


def PROJECTS = []

pipeline {
    agent {
        kubernetes {
            inheritFrom 'node-18-npm-9'
        }
    }

    stages {
        stage('acquire-applications-api') {
            when {
                changeset "packages/acquire-applications-api/**"
            }
            steps {
                script {
                    PROJECTS = PROJECTS + ['acquire-applications-api']
                }
            }
        }
        stage('acquire-quote-api') {
            when {
                changeset "packages/acquire-quote-api/**"
            }
            steps {
                script {
                    PROJECTS = PROJECTS + ['acquire-quote-api']
                }
            }
        }
        stage('mock-fast-api') {
            when {
                changeset "packages/mock-fast-api/**"
            }
            steps {
                script {
                    PROJECTS = PROJECTS + ['mock-fast-api']
                }
            }
        }
        stage('Dynamic'){
            steps{
                script {
                    def executions = PROJECTS.collectEntries { PROJECT ->
                        ["Execution ${PROJECT}": {
                            stage(PROJECT) {
                                build job: '/Product-Acquire/acquire-apps-CI', propagate: true,
                                    parameters: [
                                        string(name: 'GIT_REF', value: BRANCH_NAME),
                                        string(name: 'PROJECT', value: PROJECT)
                                    ]
                            }
                        }]
                    } 
                    parallel executions
                }
            }
        }
    }
}